import { StyleSheet } from "react-native";
import { font } from "@/design/typography";

export const appleLiquidGlassPreviewStyles = StyleSheet.create({
  stage: {
    flex: 1,
    backgroundColor: "#06152D",
  },
  scrollContent: {
    paddingBottom: 150,
  },
  heroSection: {
    minHeight: 620,
    paddingHorizontal: 18,
    paddingTop: 34,
    justifyContent: "space-between",
  },
  heroCard: {
    height: 430,
    borderRadius: 30,
    overflow: "hidden",
    backgroundColor: "#13C9C1",
    shadowColor: "#000000",
    shadowOpacity: 0.24,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 18 },
  },
  heroCyanPane: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 146,
    backgroundColor: "#36E7D7",
  },
  heroBluePane: {
    position: "absolute",
    top: 104,
    left: 64,
    right: 0,
    height: 192,
    borderTopLeftRadius: 46,
    backgroundColor: "#0E6DFF",
  },
  heroMintPane: {
    position: "absolute",
    top: 236,
    left: 0,
    width: "58%",
    height: 154,
    borderTopRightRadius: 38,
    backgroundColor: "#7BF4D3",
  },
  heroRosePane: {
    position: "absolute",
    right: 28,
    bottom: 34,
    width: 128,
    height: 128,
    borderRadius: 30,
    backgroundColor: "#FF6CB7",
  },
  heroNavyPane: {
    position: "absolute",
    left: 22,
    right: 22,
    bottom: 20,
    minHeight: 86,
    borderRadius: 24,
    padding: 18,
    justifyContent: "space-between",
    backgroundColor: "rgba(5,24,63,0.70)",
  },
  heroKicker: {
    fontFamily: font.sansBold,
    fontSize: 11,
    letterSpacing: 0,
    color: "rgba(255,255,255,0.70)",
  },
  heroCode: {
    fontFamily: font.mono,
    fontSize: 34,
    letterSpacing: 0,
    color: "#FFFFFF",
  },
  controls: {
    gap: 12,
    paddingBottom: 96,
  },
  segmentedControl: {
    flexDirection: "row",
    padding: 3,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  segment: {
    flex: 1,
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
  },
  segmentActive: {
    backgroundColor: "rgba(255,255,255,0.20)",
  },
  segmentText: {
    fontFamily: font.sansBold,
    fontSize: 11,
    letterSpacing: 0,
    color: "rgba(255,255,255,0.72)",
  },
  segmentTextActive: {
    color: "#FFFFFF",
  },
  iconSelector: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  selectorButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.10)",
  },
  selectorButtonActive: {
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  slowButton: {
    minWidth: 76,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.10)",
  },
  slowButtonText: {
    fontFamily: font.sansBold,
    fontSize: 11,
    letterSpacing: 0,
    color: "#FFFFFF",
  },
  feedSection: {
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 36,
    backgroundColor: "#E9FBFF",
  },
  contentRow: {
    minHeight: 108,
    borderRadius: 26,
    padding: 18,
    justifyContent: "space-between",
  },
  teal: {
    backgroundColor: "#22D3C5",
  },
  blue: {
    backgroundColor: "#1D73FF",
  },
  pink: {
    backgroundColor: "#FF5FA8",
  },
  mint: {
    backgroundColor: "#9DF2C6",
  },
  contentLabel: {
    fontFamily: font.sansBold,
    fontSize: 12,
    letterSpacing: 0,
    color: "rgba(1,18,45,0.62)",
  },
  contentValue: {
    fontFamily: font.mono,
    fontSize: 30,
    letterSpacing: 0,
    color: "#FFFFFF",
  },
  darkSection: {
    minHeight: 420,
    gap: 16,
    paddingHorizontal: 18,
    paddingVertical: 42,
    backgroundColor: "#071021",
  },
  darkTitle: {
    fontFamily: font.sansBold,
    fontSize: 12,
    letterSpacing: 0,
    color: "rgba(255,255,255,0.72)",
  },
  darkPanel: {
    minHeight: 230,
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: "#0C244A",
  },
  darkStripe: {
    height: 104,
    backgroundColor: "#106AE5",
  },
  darkStripeSoft: {
    height: 88,
    marginTop: 24,
    marginHorizontal: 22,
    borderRadius: 22,
    backgroundColor: "rgba(73,235,216,0.42)",
  },
  glassDock: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 32,
    alignItems: "center",
  },
  boxNone: {
    pointerEvents: "box-none",
  },
});
